### ISSUE TITLE
Error with a repo without description

### ISSUE THREAD

**Issue by masipcat** [vangheem/opencoverage#2]
This happens with a repo without a description

```
api_1       | INFO:opencoverage.taskrunner:Running task: coveragereport: 1
api_1       | ERROR:opencoverage.taskrunner:Error running task
api_1       | Traceback (most recent call last):
api_1       |   File "/app/opencoverage/taskrunner.py", line 92, in _run_tasks
api_1       |     await self.run_task(task)
api_1       |   File "/app/opencoverage/taskrunner.py", line 110, in run_task
api_1       |     await func(self, config)
api_1       |   File "/app/opencoverage/tasks.py", line 32, in run_coverage_report
api_1       |     await reporter(coverage_data=config.data)
api_1       |   File "/app/opencoverage/reporter.py", line 47, in __call__
api_1       |     pulls = await self.scm.get_pulls(self.organization, self.repo, self.commit)
api_1       |   File "/app/opencoverage/clients/scm/github.py", line 249, in get_pulls
api_1       |     gpull = GithubPull.parse_obj(item)
api_1       |   File "pydantic/main.py", line 520, in pydantic.main.BaseModel.parse_obj
api_1       |   File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
api_1       | pydantic.error_wrappers.ValidationError: 2 validation errors for GithubPull
api_1       | head -> repo -> description
api_1       |   none is not an allowed value (type=type_error.none.not_allowed)
api_1       | base -> repo -> description
api_1       |   none is not an allowed value (type=type_error.none.not_allowed)
api_1       | ERROR:opencoverage.taskrunner:Marking task in error: coveragereport: 1
```

https://github.com/vangheem/opencoverage/blob/e77d32908aac047be542273c64498289bb4fbf9e/opencoverage/clients/scm/github.py#L39

**Comment by vangheem** [comment]
This should be fixed now.
